//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOrd_Card_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int CardID { get; set; }
        public int UserID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
    }
}
